### PR TITLE
Resize level badges to 10% of original size

### PR DESCRIPTION
**Pull request by laurentS**
This PR works towards #562 by resizing the badge sizes which I found to weigh about 15MB using android studio's APK analyzer (docs [here](https://developer.android.com/studio/debug/apk-analyzer):
image

On the screenshot above, `res` contains all the images in the app. The 36 biggest ones are the level badges, which all weigh between 450 and 600kB because we have them saved as 2048x2048px images. We only display them as 150x150px in the app, so I resized to 205x205px (in case some phones have bigger screens than mine), which shaves about 15MB off the resulting APK (I don't know about the iOS IPA)

@jhenshall I'd love it if you could point your x-ray eyes at 2.1.6(3) and let me know if you can spot any difference (you shouldn't find any, hopefully).

### CODE REVIEW

**Comment by Hagellach37** [comment]
Hey, looks good to me. You cancelled the tests, but I guess as we didn't change anything else in the code this should be fine.

**Review by Hagellach37 — APPROVED** [review]
Hey,
only one quick comment. You still keep the badges in the fullsize in the repo. They will not be part of the apk, right?

**Comment by laurentS** [comment]
> Hey, only one quick comment. You still keep the badges in the fullsize in the repo. They will not be part of the apk, right?

I kept them in there so that we can create other sizes in the future from them. As far as I understand from checking with the APK inspector, the files don't end up in there, so it should be fine. (In my test, the APK size dropped from 55 to 40MB approx, which matches the drop in filesize.)

**Review by jhenshall — APPROVED** [review]
Nice one man! So I can see a small difference when comparing the screenshots of page but it is negligible for the saving in space. I wonder if bigger screen sizes might show them bigger though and so more noticeable? I think fine to press on but definitely keep the originals as you've said in case we need to resize in future.

**Pull request merged**
