### PR TITLE
Update LoadMore.js

### PR DESCRIPTION
**Pull request by kmpoppe**
Beautify the Sync Alert message.

I would have added the text to the en.json for translation but I wasn't able to find a file with the currently used 70 strings.

### CODE REVIEW

**Comment by kmpoppe** [comment]
@laurentS Would that changed string magically get into the en.json? Or do you have to manually do that?

**Comment by laurentS** [comment]
> @laurentS Would that changed string magically get into the en.json? Or do you have to manually do that?

I wish it happened automatically! For now, you need to add the marked string manually into `en.json`. There are tools to automate this process, I just haven't managed to get any of the few I tried to work properly.

**Comment by laurentS** [comment]
However, the string you changed is not marked for translation yet. I believe it has been done as part of https://github.com/mapswipe/mapswipe/pull/245 which I'm working on right now. I suggest you let me merge that PR, and then reapply your changes on top of it. I'll ping you here when it's done.

**Comment by kmpoppe** [comment]
Yep, it's there (https://github.com/mapswipe/mapswipe/pull/245/files#diff-772a593ff61f0e484d43cc349a5ab31cR78).

Just give me a nudge, and I'll change the en.json and revert the change to LoadMore.js.

**Comment by laurentS** [comment]
@kmpoppe I've merged #245 now, so you should be able to update the text from `dev`. Feel free to open a fresh PR if it's easier!

**Comment by kmpoppe** [comment]
Yeah ... As I based this change on the master branch and you, quite rightly, updated the dev branch I just made a new PR, that works better :)
Replaced by #256

**Pull request closed without merging**
