### PR TITLE
Limit nickname to one line

### PR DESCRIPTION
**Pull request by Birnbaum2001**
* and by that prevent that it overlaps with the label
  below about the completed tasks

### CODE REVIEW

**Comment by Birnbaum2001** [comment]
How do I link the issue? This will fix #135

**Comment by laurentS** [comment]
Code-wise, it's fine by me (the tests don't pass for security reasons, see #137). @jhenshall what do you think of the design aspect?

**Comment by jhenshall** [comment]
I think this is a great interim whilst the page is in the process of being fully redesigned with the rest of the UI. Good to know this is a potential issue so we can avoid it happening on the new designs, but I think great to have this for the meantime.

**Comment by laurentS** [comment]
Hi @Birnbaum2001 
I would suggest opening a separate PR for unrelated changes. The nickname fix should be one PR, and the "swipe red" another one. Typically, you would create a distinct branch for each feature on your repo, and then create PR for each of them. Please open PRs against out `dev` branch, not `master`.
As I write this, I realise you committed on top of `master`. I only wrote the docs last night, so you couldn't know :)
Here's how you can do it:
```
git clone <your forked repo> # you've already done this
git checkout dev  # to get onto our dev branch, which should be the base of all your changes
# now create a new "feature branch" for the nickname feature, called "limit-nickname"
git checkout -b limit-nickname
# you're now on the limit-nickname branch, do your changes for that feature
# when you're done, git commit/push to a branch called limit-nickname in your repo
# now open the PR from your feature branch onto `dev` (the main one in mapswipe/mapswipe)
```
then for the next feature:
```
# merge the changes from mapswipe/mapswipe/dev into your repo's dev branch if any
git checkout dev
git checkout -b another-feature
# and so on
```
The logic is that if you fork the main repo, you should avoid committing directly in the same branch as the main repo (so avoid `master` and `dev`) in your repo, or you will end up having conflicts everywhere, and it becomes horrible.

Can I suggest we forget this PR, and you open 2 new ones for the 2 fixes you've written (the code is fine)? When you do that, I'll  merge them right away into dev, and we can release a new test version to see how users like your changes on the swipe.

If any of the above doesn't make sense, please let me know!

**Comment by Birnbaum2001** [comment]
okay. let me start over.... closing this one

**Pull request closed without merging**
